name: Hourly update to Database

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
        TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
      run: |
        python3 Driver.py
